export const UPDATE_SESSION = 'UPDATE_SESSION';
export const GET_RANKBOARDS = 'GET_RANKBOARDS';
export const UPDATE_RANKBOARDS = 'UPDATE_RANKBOARDS';
export const ADD_RESPONSE = 'ADD_RESPONSE';
export const GET_RESPONSES = 'GET_RESPONSES';
export const UPDATE_RESPONSES = 'UPDATE_RESPONSES';
